export const FIND_ALL_DELEGATEES_REQUESTED = 'FIND_ALL_DELEGATEES_REQUESTED' as const;
export const FIND_ALL_DELEGATEES_SUCCEEDED = 'FIND_ALL_DELEGATEES_SUCCEEDED' as const;
export const FIND_ALL_DELEGATEES_FAILED = 'FIND_ALL_DELEGATEES_FAILED' as const;

export const REGISTER_DELEGATEE_REQUESTED = 'REGISTER_DELEGATEE_REQUESTED' as const;
export const REGISTER_DELEGATEE_SUCCEEDED = 'REGISTER_DELEGATEE_SUCCEEDED' as const;
export const REGISTER_DELEGATEE_FAILED = 'REGISTER_DELEGATEE_FAILED' as const;

export const REMOVE_DELEGATEE_REQUESTED = 'REMOVE_DELEGATEE_REQUESTED' as const;
export const REMOVE_DELEGATEE_SUCCEEDED = 'REMOVE_DELEGATEE_SUCCEEDED' as const;
export const REMOVE_DELEGATEE_FAILED = 'REMOVE_DELEGATEE_FAILED' as const;
