export const FETCH_ORGANIZATIONS_REQUESTED =
  'FETCH_ORGANIZATIONS_REQUESTED' as const;
export const FETCH_ORGANIZATIONS_SUCCEEDED =
  'FETCH_ORGANIZATIONS_SUCCEEDED' as const;
export const FETCH_ORGANIZATIONS_FAILED = 'FETCH_ORGANIZATIONS_FAILED' as const;
export const FETCH_ORGANIZATION_REQUESTED =
  'FETCH_ORGANIZATION_REQUESTED' as const;
export const FETCH_ORGANIZATION_SUCCEEDED =
  'FETCH_ORGANIZATION_SUCCEEDED' as const;
export const FETCH_ORGANIZATION_FAILED = 'FETCH_ORGANIZATION_FAILED' as const;
