export const FIND_ONE_DELEGATEE_REQUESTED = 'FIND_ONE_DELEGATEE_REQUESTED' as const;
export const FIND_ONE_DELEGATEE_SUCCEEDED = 'FIND_ONE_DELEGATEE_SUCCEEDED' as const;
export const FIND_ONE_DELEGATEE_FAILED = 'FIND_ONE_DELEGATEE_FAILED' as const;
