export const FETCH_DATA_SOURCES_REQUESTED =
  'FETCH_DATA_SOURCES_REQUESTED' as const;
export const FETCH_DATA_SOURCES_SUCCEEDED =
  'FETCH_DATA_SOURCES_SUCCEEDED' as const;
export const FETCH_DATA_SOURCES_FAILED = 'FETCH_DATA_SOURCES_FAILED' as const;

export const REGISTER_DATA_SOURCE_REQUESTED =
  'REGISTER_DATA_SOURCE_REQUESTED' as const;
export const REGISTER_DATA_SOURCE_SUCCEEDED =
  'REGISTER_DATA_SOURCE_SUCCEEDED' as const;
export const REGISTER_DATA_SOURCE_FAILED =
  'REGISTER_DATA_SOURCE_FAILED' as const;

export const UPDATE_DATA_SOURCE_REQUESTED =
  'UPDATE_DATA_SOURCE_REQUESTED' as const;
export const UPDATE_DATA_SOURCE_SUCCEEDED =
  'UPDATE_DATA_SOURCE_SUCCEEDED' as const;
export const UPDATE_DATA_SOURCE_FAILED = 'UPDATE_DATA_SOURCE_FAILED' as const;

export const HARVEST_DATA_SOURCE_REQUESTED =
  'HARVEST_DATA_SOURCE_REQUESTED' as const;
export const HARVEST_DATA_SOURCE_SUCCEEDED =
  'HARVEST_DATA_SOURCE_SUCCEEDED' as const;
export const HARVEST_DATA_SOURCE_FAILED = 'HARVEST_DATA_SOURCE_FAILED' as const;

export const REMOVE_DATA_SOURCE_REQUESTED =
  'REMOVE_DATA_SOURCE_REQUESTED' as const;
export const REMOVE_DATA_SOURCE_SUCCEEDED =
  'REMOVE_DATA_SOURCE_SUCCEEDED' as const;
export const REMOVE_DATA_SOURCE_FAILED = 'REMOVE_DATA_SOURCE_FAILED' as const;

export const HARVEST_STATUS_REQUESTED = 'HARVEST_STATUS_REQUESTED' as const;
export const HARVEST_STATUS_SUCCEEDED = 'HARVEST_STATUS_SUCCEEDED' as const;
export const HARVEST_STATUS_FAILED = 'HARVEST_STATUS_FAILED' as const;
